### ISSUE TITLE
Add app to F-Droid

### ISSUE THREAD

**Issue by thgoebel** [ProtonVPN/android-app#1]
Now that ProtonVPN for Android is open source, it would be awesome to have it included in [F-Droid](https://f-droid.org/).

A guide is available [here](https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md#adding-a-new-app).

**Comment by AlgirdasPundzius** [comment]
Thanks for suggestion. This task is actually already planned to be done in upcoming months :)

**Comment by easyKL** [comment]
F-Droid's _Request For Packaging:_
https://gitlab.com/fdroid/rfp/issues/1206
It won't succeed if Firebase it's still used...

Remember: everybody can request apps to be packaged, build and distributed via F-Droid's mainline repository https://gitlab.com/fdroid/rfp

**Comment by AlgirdasPundzius** [comment]
☝️ Correct. App does not have any direct dependency on firebase.

**Comment by licaon-kter** [comment]
Trying to build this, but the final gradle does not copy the `no/pie_openvpn` binaries to the app assets folder, what am i missing?

**Comment by AlgirdasPundzius** [comment]
@licaon-kter I guess you are trying to build release. With what commands are you running to build? 

Could you try
```
    - ./gradlew openvpn:assemble
    - ./gradlew assembleProdRelease -PabiSplit -PbuildUniversalApk
```

**Comment by licaon-kter** [comment]
`assembleProdRelease` does not copy those? I need those props too?

It already builds one with all the libs arches, but none of the binaries.

**Comment by AlgirdasPundzius** [comment]
Technically it should. But for some reason it doesn't. Having `gradlew openvpn:assemble` does the work as a workaround. We actually did not fully investigated that issue as both openvpn/strongswan are challenging modules to work with so we have continued to use this workaround in our build process for openvpn part.

**Comment by licaon-kter** [comment]
Can you move the screenshots under images/ like here: https://gitlab.com/snippets/1895688

FYI: https://gitlab.com/fdroid/fdroiddata/-/commit/28339478815bf489b7855fb1f08f5cddc25ac699

**Comment by AlgirdasPundzius** [comment]
Great news. Thank you and sorry that the build process was complicated.

We will move screenshots like you asked in upcoming release

**Comment by licaon-kter** [comment]
For the future, maybe try to integrate Strongswan in gradle like you did for Openvpn so everything is easier.

**Comment by AlgirdasPundzius** [comment]
Moved screenshots to correct folder. 

I do agree it should be integrated like OpenVPN, but haven't found an easy way to include it in similar way (as OpenVPN) and don't break building on Windows (strongswan is hell to build on Windows). And we do want our app to be buildable easily for contributors (even those on Windows) out of the box. But we might spend more time on this in future

**Comment by licaon-kter** [comment]
The app was build yesterday: https://f-droid.org/wiki/page/ch.protonvpn.android/lastbuild_20103 now we wait for sign & publish, soon.... I guess.

Regarding the integration, I hope the metadata recipe helps: https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/ch.protonvpn.android.yml#L38

**Comment by Monirzadeh** [comment]
it crash

**Comment by licaon-kter** [comment]
```
05-07 14:15:38.929 21767 21767 E AndroidRuntime: Process: ch.protonvpn.android, PID: 21767
05-07 14:15:38.929 21767 21767 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.protonvpn.android.ProtonApplication: io.sentry.dsn.InvalidDsnException: Invalid DSN, the following properties aren't set '[host]'
05-07 14:15:38.929 21767 21767 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(Unknown Source:1449)
05-07 14:15:38.929 21767 21767 E AndroidRuntime:        at android.app.ActivityThread.access$1400(Unknown Source:0)
05-07 14:15:38.929 21767 21767 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(Unknown Source:710)
05-07 14:15:38.929 21767 21767 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Unknown Source:19)
05-07 14:15:38.929 21767 21767 E AndroidRuntime:        at android.os.Looper.loop(Unknown Source:242)
05-07 14:15:38.929 21767 21767 E AndroidRuntime:        at android.app.ActivityThread.main(Unknown Source:98)
05-07 14:15:38.929 21767 21767 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
05-07 14:15:38.929 21767 21767 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
05-07 14:15:38.929 21767 21767 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(Unknown Source:275)
05-07 14:15:38.929 21767 21767 E AndroidRuntime: Caused by: io.sentry.dsn.InvalidDsnException: Invalid DSN, the following properties aren't set '[host]'
05-07 14:15:38.929 21767 21767 E AndroidRuntime:        at io.sentry.dsn.Dsn.validate(Dsn.java:222)
05-07 14:15:38.929 21767 21767 E AndroidRuntime:        at io.sentry.dsn.Dsn.<init>(Dsn.java:66)
05-07 14:15:38.929 21767 21767 E AndroidRuntime:        at io.sentry.dsn.Dsn.<init>(Dsn.java:41)
05-07 14:15:38.929 21767 21767 E AndroidRuntime:        at io.sentry.SentryClientFactory.instantiateFrom(SentryClientFactory.java:114)
05-07 14:15:38.929 21767 21767 E AndroidRuntime:        at io.sentry.SentryOptions.<init>(SentryOptions.java:44)
05-07 14:15:38.929 21767 21767 E AndroidRuntime:        at io.sentry.SentryOptions.from(SentryOptions.java:89)
05-07 14:15:38.929 21767 21767 E AndroidRuntime:        at io.sentry.SentryOptions.defaults(SentryOptions.java:116)
05-07 14:15:38.929 21767 21767 E AndroidRuntime:        at io.sentry.Sentry.init(Sentry.java:110)
05-07 14:15:38.929 21767 21767 E AndroidRuntime:        at com.protonvpn.android.ProtonApplication.initSentry(ProtonApplication.java:93)
05-07 14:15:38.929 21767 21767 E AndroidRuntime:        at com.protonvpn.android.ProtonApplication.onCreate(ProtonApplication.java:71)
05-07 14:15:38.929 21767 21767 E AndroidRuntime:        at android.app.Instrumentation.callApplicationOnCreate(Unknown Source:0)
05-07 14:15:38.929 21767 21767 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(Unknown Source:1209)
05-07 14:15:38.929 21767 21767 E AndroidRuntime:        ... 8 more
```
Oh ffs.... how do we fix this? What is missing?

**Comment by Namnodorel** [comment]
See #23 :

> Yup, this one impacts F-droid builds. Somehow didn't thought about that scenario on F-droid builds.. Will provide a fix to master soon for nullable SentryDSN value on release builds

**Comment by AlgirdasPundzius** [comment]
Fixed in [2.1.7](https://github.com/ProtonVPN/android-app/releases/tag/2.1.7)

@licaon-kter how do we get F-droid to update, do tagged releases from github get picked up automatically by F-droid or there is some manual intervetion for that to happen ?

**Comment by licaon-kter** [comment]
I'm buildtesting now....

**Comment by licaon-kter** [comment]
Fixed https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6743 but will be build next cycle (there's one running now)

**Comment by AlgirdasPundzius** [comment]
So to clarify, each update needs to be manually added and merged to f-droid data ? They don't get picked up automatically by tags ? I'm asking because it seems troublesome from F-droid perspective, and eventually would like to provide as much as possible so there is as little manual job required on F-droid as possible

**Comment by licaon-kter** [comment]
Nope, https://github.com/ProtonVPN/android-app/blob/0fd5b6026fc54405801f96da652dfe8aed1ca93e/app/build.gradle#L301 we can't handle this at the moment so each new version needs to be added manually and merged by a member once checked.

If you had that as static here: https://github.com/ProtonVPN/android-app/blob/0fd5b6026fc54405801f96da652dfe8aed1ca93e/app/build.gradle#L173 or really somewhere else where we could grep it, we could use autoupdate.

**Comment by AlgirdasPundzius** [comment]
Would having version stored somewhere in metadata folder be good enough ? Like fdroidVersion.txt with latest versionCode for latest tag ?

**Comment by licaon-kter** [comment]
```
AutoUpdateMode: Version v%c
UpdateCheckMode: HTTP
UpdateCheckData: https://raw.githubusercontent.com/Anuken/MindustryBuilds/master/version_fdroid.txt|versionCode=(.*)|.|versionName=(.*)
```
eg. https://github.com/Anuken/MindustryBuilds/blob/master/version_fdroid.txt

**Comment by kaplun** [comment]
> Fixed https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6743 but will be build next cycle (there's one running now)

I @licaon-kter , was there any problem in building the fixed version 2.1.7? At the moment https://f-droid.org/en/packages/ch.protonvpn.android/ gives a 404.

**Comment by licaon-kter** [comment]
Yes, the fixed version metadata was missing the libgmp-dev installation, not sure how that got away, so it failed to build. It's fixed now. I've also removed the broken build hence 404.

**Comment by kaplun** [comment]
Gotcha. Is there a place where we would also be able to see the pipeline with the build for our app? To have a bit of visibility and being able to assist, should it be needed?

**Comment by licaon-kter** [comment]
Main buildserver _(timezone is UTC)_: https://f-droid.org/wiki/index.php?title=Special:RecentChanges&days=7&from=&hidebots=0&hideanons=1&hideliu=1&limit=500

Your app: https://f-droid.org/wiki/index.php?title=ch.protonvpn.android/lastbuild

Your app, last short log per version code: https://f-droid.org/wiki/page/ch.protonvpn.android/lastbuild_20107_VERSIONCOE _(this gets overwritten by a  new try if the previous one was failed)_

Your app, full log published even if build failed: https://f-droid.org/repo/ch.protonvpn.android_VERSIONCODE.log.gz

**Comment by vdbhb59** [comment]
> Yes, the fixed version metadata was missing the libgmp-dev installation, not sure how that got away, so it failed to build. It's fixed now. I've also removed the broken build hence 404.

Hi Mate, I can see the build succeeded yesterday: https://f-droid.org/wiki/page/ch.protonvpn.android/lastbuild_20107
How long does it take to be up on F-Droid, once it is built?

**Comment by licaon-kter** [comment]
Yes, already published, pull-to-refresh your F-Droid index and test ;)

**Comment by kaplun** [comment]
Hey @licaon-kter thanks a lot for all the support! I managed to download it and this time no crashes. It works :muscle:
