### ISSUE TITLE
Missing plural forms

### ISSUE THREAD

**Issue by mKoonrad** [ProtonVPN/android-app#10]
You need to add to these strings plural forms (one, few and many) for upcoming localization project.
https://github.com/ProtonVPN/android-app/blob/5e2350c89b3863b28300b76d395d9de7273a62a7/app/src/main/res/values/strings.xml#L266
https://github.com/ProtonVPN/android-app/blob/5e2350c89b3863b28300b76d395d9de7273a62a7/app/src/main/res/values/strings.xml#L267

**Comment by mateusz-markowicz** [comment]
New <plural> strings were added and are now available in crowdin
