### ISSUE TITLE
Protocols

### ISSUE THREAD

**Issue by asadayaz** [ProtonVPN/android-app#104]
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [ ] I have searched open and closed issues for duplicates
- [ ] This isn't a feature request
- [ ] This is not a report about my app not working as expected

----------------------------------------

Why none of the protocols work in Iran

**Comment by kylekatarnls** [comment]
Only the Stealth protocol get a chance to pass if the provider/country has anti-VPN censorship mesures.

Also they can block by IP, which if you try different random servers you may also get a chance to find one server IP not being blocked.

**Comment by asadayaz** [comment]
Unfortunately, none of the protocols work in Iran

**Comment by mateusz-markowicz** [comment]
Please use "Report an issue" in the app and make sure "Send error logs" is checked. We need logs to see what exactly is the problem in your case.
