### ISSUE TITLE
No apk this time?

### ISSUE THREAD

**Issue by Grkrz** [ProtonVPN/android-app#105]
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [ ] I have searched open and closed issues for duplicates
- [ ] This isn't a feature request
- [ ] This is not a report about my app not working as expected

----------------------------------------

**Comment by mateusz-markowicz** [comment]
All our recent releases seem to have apks attached.
