### ISSUE TITLE
Download of rd.txt & td.txt automatically

### ISSUE THREAD

**Issue by RasheedAZ** [ProtonVPN/android-app#114]
- [x] I have searched open and closed issues for duplicates
- [x] This isn't a feature request
- [x] This is not a report about my app not working as expected
----------------------------------------
Hi. Thanks for developing and maintaining this awesome open source vpn. I noticed after connecting with ProtonVPN to a WiFi network on Android that the Android download manager was downloading 2 files by itself without any interaction from me:
- rd.txt
- td.txt

I wasn't doing any internet related things or using any internet connected apps
at the that time or even before...

I tried searching for the files in the file manager but couldn't find them. 

Can you please help me find if ProtonVPN downloaded the files or some other app?

Thanks.

**Comment by mateusz-markowicz** [comment]
It doesn't look like anything our app is downloading, we don't initiate any downloads with download manager.
