### ISSUE TITLE
ProtonVPN v4.8.63.0 (shown in Play Store) be added to GitHub?

### ISSUE THREAD

**Issue by TreadGainfully** [ProtonVPN/android-app#117]
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [x] I have searched open and closed issues for duplicates
- [x] This isn't a feature request
- [x] This is not a report about my app not working as expected

----------------------------------------
Hello,

As of Nov 22, 2023, the Google Play Store shows that the most recent version of ProtonVPN for Android is v4.8.63.0. It was updated on Nov 16, 2023, as shown at this link.

https://play.google.com/store/apps/details?id=ch.protonvpn.android

Will v4.8.63.0 be made available at GitHub as well? As of Nov 22, 2023, the most recent release is v4.8.38.0, updated on Nov 9, 2023. 

https://github.com/ProtonVPN/android-app/releases

Thank you.

**Comment by mateusz-markowicz** [comment]
Hello, 4.8.70.0 is now available on GitHub (4.8.63.0 was skipped)
