### ISSUE TITLE
String doesn't fit in different contexts

### ISSUE THREAD

**Issue by mKoonrad** [ProtonVPN/android-app#12]
For upcoming localization project you need to add this string 2 times. Once for excluded apps, second time for excluded IP address. For example in Polish we have another form to say
- excluded (in context of app)  = wykluczon**a**
- excluded (in context of IP address) = wykluczon**y**

https://github.com/ProtonVPN/android-app/blob/5e2350c89b3863b28300b76d395d9de7273a62a7/app/src/main/res/values/strings.xml#L269

**Comment by mateusz-markowicz** [comment]
This actually is used only for IPs so we won't need 2 strings. We should change the name of that string though so it reflects that it's about IPs. Not sure if such rename would be handled nicely by crowdin, so that all existing translations would be retained.

**Comment by mKoonrad** [comment]
@mateusz-markowicz Thanks for info. So I will translate existing string in IP address context.
