### ISSUE TITLE
Updating GitHub ProtonVPN to v5.1.82.0?

### ISSUE THREAD

**Issue by TreadGainfully** [ProtonVPN/android-app#129]
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [x] I have searched open and closed issues for duplicates
- [x] This isn't a feature request
- [x] This is not a report about my app not working as expected

----------------------------------------

Hello,

As of March 27, 2024, the Google Play Store shows that the most recent version of ProtonVPN for Android is v5.1.82.0. The ProtonVPN app in the Android Play Store was last updated on March 25, 2024.  https://play.google.com/store/apps/details?id=ch.protonvpn.android

The most recent GitHub release is v5.1.51.3, last updated on March 20, 2024.  https://github.com/ProtonVPN/android-app/releases

Will ProtonVPN v5.1.82.0 also be made available on GitHub? 

Thank you, Proton team, for your support.

**Comment by mateusz-markowicz** [comment]
Done. Normally github release happens once we finish rolling-out to google play.
