### ISSUE TITLE
Include sha-256 Hash of Developer Signing Key in README

### ISSUE THREAD

**Issue by shrimprugbysnowowl** [ProtonVPN/android-app#138]
Checklist:
- [x] I have searched open and closed issues for duplicates
- [x] This isn't a feature request
- [x] This is not a report about my app not working as expected

----------------------------------------
ProtonVPN is available on f-droid and that version is [built and signed by fdroid](https://github.com/ProtonVPN/android-app/issues/85). Some consider this a security issue, so apps like [Obtainium](https://github.com/ImranR98/Obtainium) that track updates to repos directly are getting more popular. It would be useful if Proton included the sha-256 hash of the proton developer's signing key in the README here so users who download and install the apk from github can verify the build. This is easily done with [AppVerifier](https://github.com/soupslurpr/AppVerifier) and its integration with Obtainium.

The hash appears to be: `DC:C9:43:9E:C1:A6:C6:A8:D0:20:3F:34:23:EE:42:BC:C8:B9:70:62:8E:53:CB:73:A0:39:3F:39:8D:D5:B8:53`, if you wouldn't mind confirming.

Thank you for your consideration.

**Comment by mateusz-markowicz** [comment]
done. thank you for the report
