### ISSUE TITLE
Uninstall / Reinstall With Latest Update

### ISSUE THREAD

**Issue by Gitchick57** [ProtonVPN/android-app#142]
I had to uninstall / reinstall app with this particular recent update.  What has changed this time?

**Comment by BHydden** [comment]
Due to #143

**Comment by AlgirdasPundzius** [comment]
Sorry this was our mistake. Please see my comment
https://github.com/ProtonVPN/android-app/issues/143#issuecomment-2303978596

Unfortunately you will need to uninstall again then going back to correctly signed version.

**Comment by Gitchick57** [comment]
No worries, thanks for the response.



Aug 22, 2024, 3:39 AM by ***@***.***:
