### ISSUE TITLE
5.5.68.0 and 5.6.8.0 are identical

### ISSUE THREAD

**Issue by BHydden** [ProtonVPN/android-app#149]
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [ x ] I have searched open and closed issues for duplicates
- [ x ] This isn't a feature request
- [ x ] This is not a report about my app not working as expected

----------------------------------------

I noticed the tags for the 2 latest releases were identical. Was this intentional?

![Screenshot_20240924-193804](https://github.com/user-attachments/assets/4d72bceb-f941-4136-8ab3-15c41437ca32)

**Comment by mateusz-markowicz** [comment]
Thank you for the report, by accident old tag was pushed as new one. It's fixed now
