### ISSUE TITLE
Still no updates on F-Droid October 2024

### ISSUE THREAD

**Issue by Oclair** [ProtonVPN/android-app#150]
![signal-2024-10-06-18-45-10-939](https://github.com/user-attachments/assets/4d57ac7d-af1d-4be5-b94a-18a8a66ec356)
update available on playstore

![signal-2024-10-06-18-45-43-304](https://github.com/user-attachments/assets/4d592775-3e6f-47c9-9d87-967284b82b83)
nothing on F-Droid for two weeks

See: https://forum.f-droid.org/t/why-some-apps-are-readily-updated-while-others-are-neglected/28455/2

Have a Nice Day!

 
Please complete the following checklist (by adding [x]):
- [x] I have searched open and closed issues for duplicates
- [x] This isn't a feature request
- [x] This is not a report about my app not working as expected

----------------------------------------

**Comment by BHydden** [comment]
This should be resolved soon. The problem was because of https://github.com/ProtonVPN/android-app/issues/149#issuecomment-2397228082

**Comment by mateusz-markowicz** [comment]
5.6.8.0 is now available on f-droid
