### ISSUE TITLE
Segfault (SEGV_MTESERR) when MTE is enabled

### ISSUE THREAD

**Issue by OneDeuxTriSeiGo** [ProtonVPN/android-app#151]
There is a known issue with the Wireguard Go implementation where Go's `GoString` implementation causes segfaults due to blowing past tagged memory boundaries. This can be seen in the go upstream in [1] with a proposal to fix this issue long term in [2]. 

Mullvad has identified a temporary solution [3] that they've deployed until the underlying issues are resolved. As MTE is being deployed in the current latest generation of Android devices and various distributions are beginning to enable this functionality (ex: GrapheneOS), it'd be ideal if a similar hotfix could be applied until the upstream go project adopts a permanent solution.

I've attached evidence of this occurring in the latest released version of ProtonVPN (sourced from F-Droid) in the form of logs from when the app crashes while transitioning from a WiFi connection to an LTE connection[4] and vice versa from an LTE connection to a WiFi connection[5]. The same issue occurs when the cellular connection changes networks.

1. https://github.com/golang/go/issues/27610
2. https://github.com/golang/go/issues/59090
3. https://github.com/mullvad/mullvadvpn-app/pull/6727
4. [Error in Proton VPN e4acf70fd0b4.txt](https://github.com/user-attachments/files/17622374/Error.in.Proton.VPN.e4acf70fd0b4.txt)
5. [Error in Proton VPN dddd8767a97b.txt](https://github.com/user-attachments/files/17622373/Error.in.Proton.VPN.dddd8767a97b.txt)

**Comment by OneDeuxTriSeiGo** [comment]
Looking into this some more, I suspect the cause is probably `wgTurnOn()`. 

The string is passed into `wgTurnOn()` [here](https://github.com/ProtonVPN/wireguard-android/blob/26822ec4034fe69ed19490b346f69a28c17c0a77/tunnel/tools/libwg-go/jni.c#L70-L79) but is then de-allocated in [the following lines](https://github.com/ProtonVPN/wireguard-android/blob/26822ec4034fe69ed19490b346f69a28c17c0a77/tunnel/tools/libwg-go/jni.c#L80-L81). 

But those strings are then further passed into [the wireguard device](https://github.com/ProtonVPN/wireguard-android/blob/26822ec4034fe69ed19490b346f69a28c17c0a77/tunnel/tools/libwg-go/api-android.go#L98-L102). So there is a likelihood that manually deep copying the `settings` and `socketType` strings on the go side of the FFI in `wgTurnOn()` would prevent any of that tagged memory from leaking in to the go library. From reading through the code in [wireguard-android](https://github.com/ProtonVPN/wireguard-android) that seems to be the only place where MTE tagged memory segments should be able to leak in.

**Comment by OneDeuxTriSeiGo** [comment]
Just making a quick note that I updated the logs to instead link to the full MTE crash traces with the specific behavior that triggers it instead of the brief trace available in the logs.

**Comment by Red6785** [comment]
Bump.

**Comment by mateusz-markowicz** [comment]
@OneDeuxTriSeiGo Thank you for your detailed report, we're looking into the issue.

**Comment by TXort** [comment]
I am experiencing the same issue. Any information about when we can expect the fix?

**Comment by FID02** [comment]
After having run version 5.8.10 beta (obtained from the Play Store) for 1-2 days, with Wireguard set as the protocol, I have so far not experienced that MTE has crashed the app when run with GrapheneOS' MTE implementation on Pixel 8. In previous versions it was very easy to reproduce, so this looks promising.

**Comment by mateusz-markowicz** [comment]
fix available on github since: https://github.com/ProtonVPN/android-app/releases/tag/5.8.15.0

**Comment by OneDeuxTriSeiGo** [comment]
I'm just coming in to report that I'm now running 5.8.15.0 from F-Droid on GrapheneOS and I am no longer seeing the errors/crashes w/ MTE enabled so the fix looks like it's working as intended.

Thank you very much for your hard work maintaining this awesome project.
