### ISSUE TITLE
How does ProtonVPN implement PiP mode?

### ISSUE THREAD

**Issue by Korb** [ProtonVPN/android-app#154]
Please complete the following checklist (by adding [x]):
- [x] I have searched open and closed issues for duplicates
- [x] This isn't a feature request
- [x] This is not a report about my app not working as expected

----------------------------------------
The ProtonVPN Android app supports **the Small Window** (aka [picture-in-picture mode](https://developer.android.com/develop/ui/compose/layouts/adaptive/support-multi-window-mode)), and it works great! The app can be displayed in Mini windows, Small window, or as a shortcut on the side of the screen. It's very convenient, and I wish more of the apps I regularly use supported this feature.

However, during [the discussion with the developers of the cgeo mapping application](https://github.com/cgeo/cgeo/issues/16347/), I found out that different mobile device manufacturers implement this function differently. At the same time, applications made by Google work properly in the PiP mode of any manufacturer, but a rare application developer manages to make their application support picture-in-picture mode not only in pure Android, but also on alternative assemblies, such as BharOS, CalyxOS, GrapheneOS, HyperOS, iodéOS, One UI, Realme UI, Shift OS, etc. Or in Funtouch OS version 14, which I am a user of.

**Comment by mateusz-markowicz** [comment]
We don't do anything specific to support window modes, our layouts in practice might just be flexible enough to handle a range of window sizes.
