### ISSUE TITLE
Split tunneling for included app only

### ISSUE THREAD

**Issue by realjench** [ProtonVPN/android-app#18]
Check box to revert choice, include/exclude

As same as ip

**Comment by realjench** [comment]
Please may you give gimme the files relatives? I'll code it, ok?

**Comment by AlgirdasPundzius** [comment]
Hello, 
The code for split tunneling dialogs is here >> 
https://github.com/ProtonVPN/android-app/tree/master/app/src/main/java/com/protonvpn/android/ui/splittunneling

Though I must also say that even if you make merge request for it, changing ADD/X to a checkbox is a design change, and I'm not sure if it will be approved by our design team. Would be better to add checkbox alongside ADD/X, so there is no need to re-enter exclusions if you want to disable them temporary, but it is still possible to remove them fully.
