### ISSUE TITLE
strongSwan or OpenVPN; which is being used?

### ISSUE THREAD

**Issue by hellogates** [ProtonVPN/android-app#2]
Hi there,
This is more of a question than an issue. First off, huge props for making your client software GPL3 not merely  just 'open source'; and having them audited by 3rd party.

From the readme file, it seemed like strongswan, which is the most actively developed ipsec implementation is being used on this project. But upon looking at the project files, I see openVPN binaries are present here. So which is being used and for what? What is the need for openVPN if strongSwan is being used? 

I'm sorry if this question sounds dumb; I'm not technically that much well versed and certainly not a java programmer. On another note, and I guess the developers of this project already know this, openvpn connections are easily detected by not so sophisticated DPI and can be killed. This is what happens in the country that I live and it's not China.

Thanks for reading.

**Comment by AlgirdasPundzius** [comment]
Hello, 

We actually use both ics-openvpn and strongswan in our app to provide both OpenVPN and IKEv2 as protocol selections for our users. So both projects are used in ProtonVPN, you can find more information about our dependencies in "Third party licenses" screen which is located inside the app in Settings screen.
