### ISSUE TITLE
DSN Errors

### ISSUE THREAD

**Issue by waltercool** [ProtonVPN/android-app#23]
Hi all,

Tried to make a production build, but got stuck with DSN Exception.

Question: What to do on that case? This is not well documented. I'm only intended to build a Debug release?

Thanks!

**Comment by waltercool** [comment]
I'm sorry, haven't attached the exception:

04-26 01:20:30.575  1401  1401 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.protonvpn.android.ProtonApplication: io.sentry.dsn.InvalidDsnException: Invalid DSN, the following properties aren't set '[host]'
04-26 01:20:30.575  1401  1401 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6465)
04-26 01:20:30.575  1401  1401 E AndroidRuntime:        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
04-26 01:20:30.575  1401  1401 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
04-26 01:20:30.575  1401  1401 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:107)
04-26 01:20:30.575  1401  1401 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
04-26 01:20:30.575  1401  1401 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7356)
04-26 01:20:30.575  1401  1401 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-26 01:20:30.575  1401  1401 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
04-26 01:20:30.575  1401  1401 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
04-26 01:20:30.575  1401  1401 E AndroidRuntime: Caused by: io.sentry.dsn.InvalidDsnException: Invalid DSN, the following properties aren't set '[host]'
04-26 01:20:30.575  1401  1401 E AndroidRuntime:        at io.sentry.dsn.Dsn.validate(Dsn.java:222)
04-26 01:20:30.575  1401  1401 E AndroidRuntime:        at io.sentry.dsn.Dsn.<init>(Dsn.java:66)
04-26 01:20:30.575  1401  1401 E AndroidRuntime:        at io.sentry.dsn.Dsn.<init>(Dsn.java:41)
04-26 01:20:30.575  1401  1401 E AndroidRuntime:        at io.sentry.SentryClientFactory.instantiateFrom(SentryClientFactory.java:114)
04-26 01:20:30.575  1401  1401 E AndroidRuntime:        at io.sentry.SentryOptions.<init>(SentryOptions.java:44)
04-26 01:20:30.575  1401  1401 E AndroidRuntime:        at io.sentry.SentryOptions.from(SentryOptions.java:89)
04-26 01:20:30.575  1401  1401 E AndroidRuntime:        at io.sentry.SentryOptions.defaults(SentryOptions.java:116)
04-26 01:20:30.575  1401  1401 E AndroidRuntime:        at io.sentry.Sentry.init(Sentry.java:110)
04-26 01:20:30.575  1401  1401 E AndroidRuntime:        at com.protonvpn.android.ProtonApplication.initSentry(ProtonApplication.java:93)
04-26 01:20:30.575  1401  1401 E AndroidRuntime:        at com.protonvpn.android.ProtonApplication.onCreate(ProtonApplication.java:71)
04-26 01:20:30.575  1401  1401 E AndroidRuntime:        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1189)
04-26 01:20:30.575  1401  1401 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
04-26 01:20:30.575  1401  1401 E AndroidRuntime:        ... 8 more

**Comment by AlgirdasPundzius** [comment]
Hey @waltercool,

You are running trying to build prodDebug variant?

**Comment by waltercool** [comment]
Hi @AlgirdasPundzius ,

Right now, yes and works fine, but tried Release and got that error mentioned above.

**Comment by lucaspape** [comment]
I have the same error using the F-Droid version on Android 10:

```


time: 1588846029523
msg: io.sentry.dsn.InvalidDsnException: Invalid DSN, the following properties aren't set '[host]'
stacktrace: java.lang.RuntimeException: Unable to create application com.protonvpn.android.ProtonApplication: io.sentry.dsn.InvalidDsnException: Invalid DSN, the following properties aren't set '[host]'
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6465)
	at android.app.ActivityThread.access$1300(ActivityThread.java:219)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
Caused by: io.sentry.dsn.InvalidDsnException: Invalid DSN, the following properties aren't set '[host]'
	at io.sentry.dsn.Dsn.validate(Dsn.java:222)
	at io.sentry.dsn.Dsn.<init>(Dsn.java:66)
	at io.sentry.dsn.Dsn.<init>(Dsn.java:41)
	at io.sentry.SentryClientFactory.instantiateFrom(SentryClientFactory.java:114)
	at io.sentry.SentryOptions.<init>(SentryOptions.java:44)
	at io.sentry.SentryOptions.from(SentryOptions.java:89)
	at io.sentry.SentryOptions.defaults(SentryOptions.java:116)
	at io.sentry.Sentry.init(Sentry.java:110)
	at com.protonvpn.android.ProtonApplication.initSentry(ProtonApplication.java:93)
	at com.protonvpn.android.ProtonApplication.onCreate(ProtonApplication.java:71)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1189)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
	... 8 more
```

**Comment by AlgirdasPundzius** [comment]
Yup, this one impacts F-droid builds. Somehow didn't thought about that scenario on F-droid builds.. Will provide a fix to master soon for nullable SentryDSN value on release builds

**Comment by AlgirdasPundzius** [comment]
Fixed in [2.1.7](https://github.com/ProtonVPN/android-app/releases/tag/2.1.7)

**Comment by thgoebel** [comment]
This is happening again to me in v2.2.2 from F-Droid.

**Comment by AlgirdasPundzius** [comment]
Ugh, yes I can confirm, we messed up here, and 2.2.2 tag does not include F-droid hotfix.. 
Will address this soon. Sorry everyone for inconvenience

**Comment by thgoebel** [comment]
See https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6894

**Comment by AlgirdasPundzius** [comment]
@thgoebel thank you for reporting this 👍 2.2.3 Release for F-droid is live on github

**Comment by floss-birdy** [comment]
yes , proton f-droid version 2.2.2 is crashing .
logs :  https://del.dog/megranyles.txt
stock android  10

**Comment by waltercool** [comment]
Many thanks, resolving this
