### ISSUE TITLE
Fastlane changelogs use versionCode

### ISSUE THREAD

**Issue by licaon-kter** [ProtonVPN/android-app#25]
eg. 20103.txt not versionName

**Comment by AlgirdasPundzius** [comment]
@licaon-kter 

We changed newest version changelog accordingly. We also added grepable version.txt 
https://github.com/ProtonVPN/android-app/blob/master/metadata/version_fdroid.txt

Is this enough for F-droid to automatically build each new release we make ? Or is there anything else we can do to help automatize building for F-droid ?

**Comment by licaon-kter** [comment]
https://gitlab.com/fdroid/fdroiddata/-/commit/bc896cc6133144d4cc4bba9f4f8f8ea2e6b4e474
