### ISSUE TITLE
Crash on starting in Persian locale

### ISSUE THREAD

**Issue by danialbehzadi** [ProtonVPN/android-app#30]
In Persian locale, app won't start.

**Comment by AlgirdasPundzius** [comment]
Can you post stacktrace, or at least market (google play/f-droid/direct) and a version which is crashing for you?

**Comment by danialbehzadi** [comment]
I get the f-droid version 2.2.2

Here is [logcat](https://github.com/ProtonVPN/android-app/files/4717867/logcat.txt)

**Comment by AlgirdasPundzius** [comment]
Ah, it's the same F-droid 2.2.2 issue which we just re-introduced accidently... Original issue -> https://github.com/ProtonVPN/android-app/issues/23#issuecomment-637456422

I would suggest to use 2.1.7 for now from F-droid until 2.2.3 is released. Sorry for inconvenience
