### ISSUE TITLE
[feature request] proper android tv support

### ISSUE THREAD

**Issue by MGThePro** [ProtonVPN/android-app#39]
As it is right now, the android app is unfortunately barely usable on android tv without a mouse and keyboard.
It rarely supports landscape mode (yet constantly switches to landscape mode for a split of a second to switch back to portrait mode again), and most options aren't accessible with just a remote. Using a mouse and keyboard helps a bit, but not much.
Allowing a functional landscape mode and making all buttons selectable with a remote directional pad would improve it a lot, for my usecase.

**Comment by AlgirdasPundzius** [comment]
Hey @MGThePro
Actually, proper TV support is in active development at the moment. So ProtonVPN app will support TV, and not just landscape mode. TV will have their own dedicated UI.
Though I can't provide any ETA yet. But can assure TV support is already in development stages

**Comment by MGThePro** [comment]
That is good to hear, hopefully it will be ready to test before my subscription runs out at the end of the year :+1:

**Comment by AlgirdasPundzius** [comment]
@MGThePro I hope we are still on time. TV support has been released, so feel free to try it :)
