### ISSUE TITLE
HTTP link instead HTTPS

### ISSUE THREAD

**Issue by mKoonrad** [ProtonVPN/android-app#4]
https://github.com/ProtonVPN/android-app/blob/387fffcb5d1a8eca71e1b0b2650567218fb8c2c3/app/src/main/res/values/strings.xml#L144

Fo security reasons you should use only https links

Edit: Also typo. Missing space between sentences.

**Comment by mateusz-markowicz** [comment]
Hello, thank you for the report. Issue is now addressed in our internal repo and fix will be available on github once we release it to production.
