### ISSUE TITLE
[Privacy] WebView

### ISSUE THREAD

**Issue by duggalsu** [ProtonVPN/android-app#50]
Opt out of sending metrics to Google when using WebView. Add the following to the manifest -
```
<meta-data android:name="android.webkit.WebView.MetricsOptOut" android:value="true" />
```
https://developer.android.com/guide/webapps/webview-privacy

**Comment by mateusz-markowicz** [comment]
Thanks! This is now fixed in our internal repo and fix will be available on github with our next public release.
