### ISSUE TITLE
Allow setting connection to unmetered

### ISSUE THREAD

**Issue by MKoesters** [ProtonVPN/android-app#52]
Hi,

I'm trying to autoupload some files to nextcloud, and it is not working with protonvpn activated.

I suspect it has something to do with this https://github.com/nextcloud/android/issues/2839.
Apparently, some VPNs are set to metered  and nextcloud has the option to only allow uploads with unmetered connections, which I want to use. 
when connecting to my home wifi with protonvpn, the autoupload is not working.
If I deactivate protonvpn it is working fine.

Some other VPN apps also had this problem, see https://github.com/blokadaorg/blokada/issues/790 and https://github.com/nextcloud/android/issues/2839#issuecomment-699970865

Could it be possible that the protonVPN connection is set as metered and if yes, is there currently an option to change this?
Since I'm always using protonVPN and only deactivated for testing purposes, I need this feature to use the autoupload functionality in nextcloud, assuming this is actually due to the metered/unmetered setting.

I'm using the protonVPN f-droid version (v 2.4.31.0) with a plus plan running on GrapheneOS (android 11).

**Comment by mateusz-markowicz** [comment]
Hey, thanks for the report. This issue was fixed in 2.6.0.0 that's also available on f-droid.
