### ISSUE TITLE
Publish v2.6.4.2 to F-Droid

### ISSUE THREAD

**Issue by SailReal** [ProtonVPN/android-app#55]
Thanks for your work!

It would be awesome, if you could publish v2.6.4.2 which is in [Github-Releases](https://github.com/ProtonVPN/android-app/releases/tag/2.6.4.2) and [Playstore](https://play.google.com/store/apps/details?id=ch.protonvpn.android) to [F-Droid](https://f-droid.org/en/packages/ch.protonvpn.android/).

I love the idea to replace my Pi-hole with NetShield on my phone but NetShield isn't available in the latest F-Droid release (v2.6.0.0).

**Comment by mateusz-markowicz** [comment]
Thanks for the report! 2.6.4.2 is now on f-droid
