### ISSUE TITLE
Login form doesn't require 2FA code

### ISSUE THREAD

**Issue by mainrs** [ProtonVPN/android-app#56]
I registered a 2FA authenticator and noticed that logging into the app doesn't prompt for the code. I had to enter the code when logging in on the beta page though.

**Comment by Ammako** [comment]
https://protonvpn.com/support/two-factor-authentication/

> ProtonVPN apps do not prompt users for 2FA during login because they do not keep any logs of user data. Thus, there is no sensitive information to protect. However, 2FA can be implemented to protect your Account settings, which contains critical information, such as your payment details.

To further clarify, all logging into the app does is let you use the VPN to connect to other servers. It doesn't let you view any sensitive information, and changing account settings requires logging into the web page for it which prompts for 2FA.

**Comment by mainrs** [comment]
Thanks for the information!
