### ISSUE TITLE
Support conversation view

### ISSUE THREAD

**Issue by jerome-tgl** [ProtonVPN/android-app#6]
Group email responses into a conversation, with the newest email at the bottom.

- If the subject line changes, break it off into a new one.
- Allow replying to (and forwarding) individual emails, similar to ProtonMail Web v3.0.
- Support actions (e.g deletion, archiving, labelling) on all emails within a conversation, from the inbox/folder/labels views.

**Comment by mateusz-markowicz** [comment]
Hello, this is a project for ProtonVPN android client, for reports regarding ProtonMail please use "Report Bugs" feature in the mail client :)
