### ISSUE TITLE
2.6.91 not available on fdroid

### ISSUE THREAD

**Issue by Thewisem** [ProtonVPN/android-app#67]
Aa the title says, the play stoore app was updated on march while the fdroid app hasn't been updated in months.

**Comment by mateusz-markowicz** [comment]
https://f-droid.org/en/packages/ch.protonvpn.android/ is showing 2.6.91.0 "Added on 2021-04-09". Is that version not accessible for you?

**Comment by bingoxo** [comment]
@mateusz-markowicz can you check for latest version : https://gitlab.com/fdroid/fdroiddata/-/issues/2458 , they say it's coming from you

**Comment by Thewisem** [comment]
Yeah its not there

**Comment by Thewisem** [comment]
The new update hasn't been released on fdroid
