### ISSUE TITLE
 Could openvpn3 code be extended to desktop?

### ISSUE THREAD

**Issue by lucaszanella** [ProtonVPN/android-app#68]
I'm integrating this code into my app. For desktop, however, it won't compile because of lzo and lz4. The failure is because it expects ANDROID_ABI to be set. Like here: https://github.com/ProtonVPN/android-app/blob/42bf1ef07ceb73461db0472a6b8d89b357fbea6b/openvpn/src/main/cpp/openssl/openssl.cmake#L684

Would a PR making it buildable in desktop be welcome?

**Comment by mateusz-markowicz** [comment]
Hey Lucas, this part comes from https://github.com/schwabe/ics-openvpn and it'd make more sense to prepare merge request to the source project (changes will reach our project through there). We try to keep our changes on top of it to minimum for less problematic updates.
