### ISSUE TITLE
Could not create symbolic link for : mbedtls 

### ISSUE THREAD

**Issue by alirkarimy** [ProtonVPN/android-app#7]
OpenVPN 2.x version 2.0.21-0-g387fffc
  OpenVPN 3.x version 2.0.21-0-g387fffc
  No such file: E:/android-vpn-app/openvpn/src/main/cpp/mbedtls/include/mbedtls/config.h
  
  CMake Error at mbedtls/CMakeLists.txt:92 (message):
    Could not create symbolic link for:
    E:\android-vpn-app\openvpn\src\main\cpp\mbedtls\include\mbedtls --> The
    system cannot find the file specified.
  
  Call Stack (most recent call first):
    mbedtls/include/CMakeLists.txt:15 (link_to_source)
  
  ___________________________________________
Android Studio Version : 3.5.3
Swig , cmake , ndk , sdk is up to date 
To Produce the Error :
Clone the source and try to build it on Win 10

CMake out put is attached 

[CMakeOutput.log](https://github.com/ProtonVPN/android-app/files/4112053/CMakeOutput.log)

**Comment by AlgirdasPundzius** [comment]
Hello, 
This seems like OpenVPN and mbedtls issue. We are working on linux which is our day-to-day environment and can't now offer support for building on other platforms
