### ISSUE TITLE
Parsing error on install 

### ISSUE THREAD

**Issue by tafkar99** [ProtonVPN/android-app#72]
Get parsing error on installing apk on fire tv and firetv stick

**Comment by mfeldt** [comment]
Same here. "Installation from unknown sources" is clearly enabled.

**Comment by guandalf** [comment]
Hello! I have just checked the installation of the APK downloaded from github.com and it's working fine here on a FireTV Stick. Parsing error seems like the APK has not been downloaded correctly/completely.
Do you mind to retry downloading it, please?

Thank you.

**Comment by tafkar99** [comment]
Looks good 

Thanks

**Comment by tafkar99** [comment]
Interesting it installed on only 1/3 firetv devices 

1 is firetv 
1 is firetvstick hd
1 is firetv stick 4k

I redownloaded the apk via downloader on each 

Only last device installed

**Comment by guandalf** [comment]
Please remember our app is compatible only with fire os >= 6

See https://protonvpn.com/support/firestick/ for details.

Inviato da iPad

> Il giorno 1 set 2021, alle ore 22:50, tafkar99 ***@***.***> ha scritto:
> 
> ﻿
> Interesting it installed on only 1/3 firetv devices 
> 
> 1 is firetv 
> 1 is firetvstick hd
> 1 is firetv stick 4k
> 
> I redownloaded the apk via downloader on each 
> 
> Only last device installed 
>

**Comment by tafkar99** [comment]
Ok that explains it
