### ISSUE TITLE
f-droid repo is out of date

### ISSUE THREAD

**Issue by michaeljensen** [ProtonVPN/android-app#76]
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [x] I have searched open and closed issues for duplicates
- [x] This isn't a feature request
- [x] This is not a report about my app not working as expected

----------------------------------------
I'm not sure if this is the correct place to ask about this, but...
It's been 26 days since the release of 2.8.75.0 and f-droid still only has version 2.7.70.0 available.
https://f-droid.org/en/packages/ch.protonvpn.android/

Is this something that can be remedied by someone here or should I ask elsewhere?

**Comment by proletarius101** [comment]
https://github.com/ProtonVPN/android-app/blob/master/metadata/version_fdroid.txt is not updated @mateusz-markowicz

**Comment by proletarius101** [comment]
Unfortunately, a binary is added: https://github.com/ProtonVPN/android-app/blob/2.8.75.0/app/libs/govpn.aar. It can't be updated until it's open-source :(

**Comment by mateusz-markowicz** [comment]
@michaeljensen thanks for the report. Said library is now open-sourced (https://github.com/ProtonVPN/go-vpn-lib) and published to maven. Next production build that will be available soon will be published on F-Droid.

**Comment by proletarius101** [comment]
> @michaeljensen thanks for the report. Said library is now open-sourced (https://github.com/ProtonVPN/go-vpn-lib) and published to maven. Next production build that will be available soon will be published on F-Droid.

Happy to hear that.

Actually, https://github.com/ProtonVPN/go-vpn-lib is still private. Can you confirm that?

**Comment by mateusz-markowicz** [comment]
@proletarius101 didn't notice it's still private, will have that fixed before the release, thanks!

**Comment by Thewisem** [comment]
Dame, thanks to that binary the fdroid version missed the entire 2.8 versions of protonvpn.
