### ISSUE TITLE
Latest version of the app F-Droid

### ISSUE THREAD

**Issue by johndoe432** [ProtonVPN/android-app#84]
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [x] I have searched open and closed issues for duplicates
- [x] This isn't a feature request
- [x] This is not a report about my app not working as expected

----------------------------------------
Latest version of the app is not yet available in F-Droid Store. The version_fdroid.txt file was not updated to the latest version.

**Comment by Uglyjoke** [comment]
Can't download it says needs authorization

**Comment by CyberaxAnnon** [comment]
Bump, any update on this?

**Comment by licaon-kter** [comment]
Latest is available, so close this as fixed?
