### ISSUE TITLE
Signature mismatch between the Google Play, Github and F-Droid APK

### ISSUE THREAD

**Issue by carlosjeurissen** [ProtonVPN/android-app#85]
It seems the app signature is different between the different distribution channels for Proton VPN. This prevents users from updating their app without loosing their data if they change distribution channels.

The build number is also inconsistent, see: https://github.com/ProtonVPN/android-app/issues/86

**Comment by waltercool** [comment]
This is not a bug. They are built and signed differently per-store.

**Comment by mateusz-markowicz** [comment]
All builds apart from from f-droid (which is build not by Proton but f-droid) use the same certificate with fingerprint: `DC:C9:43:9E:C1:A6:C6:A8:D0:20:3F:34:23:EE:42:BC:C8:B9:70:62:8E:53:CB:73:A0:39:3F:39:8D:D5:B8:53`. Switching between f-droid and other channels is indeed not possible.
