### ISSUE TITLE
Leaks outside VPN while using Hotspot

### ISSUE THREAD

**Issue by git70** [ProtonVPN/android-app#99]
Hi

Application version: 4.3.49.0
OS: Android 13
Always-on VPN & Kill-Switch: Enabled
Block Connections Without VPN: Enabled

After turning on the WiFi hotspot, the entire network traffic from the connected device leaks via ISP instead of VPN.

**Comment by mateusz-markowicz** [comment]
Thanks for the report. This is unfortunately how Android routes the hotspot traffic and can't do much about this as a VPN client. See https://protonvpn.com/support/share-vpn-connection-android-hotspot/
